environment_parameters:
  skullSpeed:
    curriculum:
      - name: skullSpeed
        value: 23.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 0.2
      - name: skullSpeed
        value: 24.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 150
          threshold: 0.4
      - name: skullSpeed
        value: 25.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 150
          threshold: 0.6
      - name: skullSpeed
        value: 26.0  

  maxSkulls:
    curriculum:
      - name: maxSkulls
        value: 3
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 200
          threshold: 0.4
      - name: maxSkulls
        value: 4
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 200
          threshold: 0.6
      - name: maxSkulls
        value: 5

  bulletSpeed:
    curriculum:
      - name: bulletSpeed
        value: 35
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 0.6
      - name: bulletSpeed
        value: 40
  


behaviors:
  PlayerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 1.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5.0e6
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
