environment_parameters:
  skullSpeed:
    curriculum:
      - name: skullSpeed
        value: 20.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
      - name: skullSpeed
        value: 25.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.7
      - name: skullSpeed
        value: 30.0

  spawnInterval:
    curriculum:
      - name: spawnInterval
        value: 3.0
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
      - name: spawnInterval
        value: 2.5
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.7
      - name: spawnInterval
        value: 2.0

  maxSkulls:
    curriculum:
      - name: maxSkulls
        value: 3
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.75
      - name: maxSkulls
        value: 5

  bulletSpeed:
    curriculum:
      - name: bulletSpeed
        value: 40
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
      - name: bulletSpeed
        value: 50
        completion_criteria:
          measure: progress
          behavior: PlayerAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.7
      - name: bulletSpeed
        value: 60

behaviors:
  PlayerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 1.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 3.0e6
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
